title = "The Bridge of Death Test"
author = "Alex Jackson"

[[flashcards]]
question = "What is your name?"
answer = "Arthur, King of the Britons"

[[flashcards]]
question = "What is your quest"
answer = "To seek the Holy Grail."

[[flashcards]]
question = "What is the airspeed velocity of an unladen swallow?"
answer = "What do you mean, an African or European swallow?"
